"use client";
import { FormEvent, useState } from "react";

type Result = { items?: { component_type?: string; product_name?: string; unit_price?: number }[]; core_total?: number; accessories_total?: number; final_total?: number; error?: string; message?: string };

const labels: Record<string,string> = { cpu:"پردازنده", cooler:"خنک‌کننده", motherboard:"مادربرد", ram:"رم", gpu:"کارت گرافیک", storage:"ذخیره‌سازی", psu:"منبع تغذیه", case:"کیس" };

export default function BuilderPage(){
 const [mode,setMode]=useState<"visual"|"compact">("visual"); const [budget,setBudget]=useState(200000000); const [purpose,setPurpose]=useState("gaming"); const [preference,setPreference]=useState("balanced"); const [resolution,setResolution]=useState("1080p"); const [loading,setLoading]=useState(false); const [result,setResult]=useState<Result|null>(null);
 async function generate(e:FormEvent){e.preventDefault();setLoading(true);setResult(null);try{const r=await fetch("/api/recommendations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({budget,purpose,preference,resolution})});setResult(await r.json())}catch{setResult({error:"Unable to contact the recommendation service."})}finally{setLoading(false)}}
 return <main className="shell"><div className="eyebrow">SmartPCBuilder / Builder</div><h1>Generate your PC</h1><div className="mode"><button className={mode==="visual"?"active":""} onClick={()=>setMode("visual")}>Visual</button><button className={mode==="compact"?"active":""} onClick={()=>setMode("compact")}>Compact / Pro</button></div><form className="card" onSubmit={generate}><div className="grid"><div className="field"><label>Budget (تومان)</label><input type="number" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></div><div className="field"><label>Purpose</label><select value={purpose} onChange={e=>setPurpose(e.target.value)}><option value="gaming">Gaming</option><option value="work">Work</option><option value="editing">Video / Content</option><option value="general">General</option></select></div><div className="field"><label>Build preference</label><select value={preference} onChange={e=>setPreference(e.target.value)}><option value="cheapest">Cheapest</option><option value="balanced">Balanced / Best Value</option><option value="performance">Performance</option><option value="premium">Premium</option></select></div><div className="field"><label>Resolution</label><select value={resolution} onChange={e=>setResolution(e.target.value)}><option>1080p</option><option>1440p</option><option>4K</option></select></div></div><br/><button className="primary" disabled={loading}>{loading?"Researching…":"Generate Build"}</button></form>{result&&<section className="card"><h2>🏆 Recommended Build</h2>{result.error?<p className="error">{result.error}</p>:result.items?.length?<div className="result">{result.items.map((x,i)=><div className="part" key={i}><span><strong>{labels[x.component_type||""]||x.component_type}</strong><br/><span className="muted">{x.product_name}</span></span><strong>{typeof x.unit_price==="number"?`${x.unit_price.toLocaleString("en-US")} تومان`:"—"}</strong></div>)}<div className="totals"><div className="total">Core Total<strong>{result.core_total?.toLocaleString("en-US")} تومان</strong></div><div className="total">Accessories<strong>{result.accessories_total?.toLocaleString("en-US")} تومان</strong></div><div className="total">Final Total<strong>{result.final_total?.toLocaleString("en-US")} تومان</strong></div></div></div>:<p className="muted">{result.message||"No complete market-backed build is available yet."}</p>}</section>}</main>
}
